### PR TITLE
Remove generated files

### PR DESCRIPTION
**Pull request by letmaik**
https://github.com/opengeospatial/CoverageJSON/pull/79 has introduced a lot of generated files by accident. This PR removes those and others that had already been there.

cc @ghobona I'm not sure if you wanted to do the cleanup yourself, but I just went ahead now, hope that's ok.

### CODE REVIEW

**Comment by ghobona** [comment]
@letmaik Yes, that's ok. Thanks.

**Comment by chris-little** [comment]
@letmaik Does this PR need re-basing now that all the others have been merged?

**Comment by letmaik** [comment]
Looks like there was another PR in the meantime that committed auto-generated files, hence the conflict. Let's see... https://github.com/opengeospatial/CoverageJSON/pull/95 Hm, that's unfortunate.
Feel free to close this PR and open another one that removes the same files and updates `.gitignore`.

**Comment by chris-little** [comment]
@ghobona Are you happy with Maik's suggestion? I have no idea where these auto-generated files are coming from . Is it part of the Metanorma processes? Are the files actually needed?

**Pull request closed without merging**
