### PR TITLE
Update document revision number to 21-069r1

### PR DESCRIPTION
**Pull request by ghobona**

### CODE REVIEW

**Comment by ghobona** [comment]
In the interest of time, since this is a minor change, I'm bypassing the branch protections.

**Comment by letmaik** [comment]
Does this have an effect on the auto-generated document? Does the link in the README have to be updated? Similarly, this would affect the link at https://covjson.org/spec/ I would assume?
Will a change to the document number happen more often?

**Comment by ghobona** [comment]
The filename of the auto-generated document has been kept the same (21-069.html) so as not to break current references to it. This is because the auto-generated document is a work-in-progress. So there is no need to change the README file. After the public review period, if there are changes to the document, there would most likely be a new revision number assigned when the document is submitted for TC Approval.

**Comment by chris-little** [comment]
@letmaik So future formally approved versions would have names like 21-069r1, 21-069r2, etc. We could also decide, if a change is required in the future, such as a new version which is not backward compatible, to request a new number, such as 22-nnn or 23-nnn. HTH.

**Pull request merged**
