### PR TITLE
Clarifications addressing #107

### PR DESCRIPTION
**Pull request by jonblower**
Addresses comments from @joanma747 (#107) regarding improving the definition of NdArrays

### CODE REVIEW

**Review by chris-little — APPROVED** [review]

**Comment by chris-little** [comment]
@jonblower I corrected the [hyper link format](https://like.this.edu), but probably got it wrong too!

**Review by chris-little — APPROVED** [review]

**Comment by joanma747** [comment]
The changes address my concern and I believe the order of the nD array is clear and the reference to the JSON RFC make it consistent. Thanks for doing this.

**Comment by jonblower** [comment]
> I'm ok with it, it's better than before. Still not formal enough but practical enough for the first release.

Yeah, I think your more formal definition was good, but I proposed a less-formal version (modelled on text from other standards like NetCDF) as I felt it was more readable. But I'm in two minds about this - not sure whether we should formalise it more. Maybe we could tighten it in a future version if people find it unclear?

**Comment by chris-little** [comment]
@jonblower @letmaik Don't forget that we will go to final public review and that might tease out the text that matter.

**Pull request merged**
